### ISSUE TITLE
Add the ability to validate extension configuration toml files.

### ISSUE THREAD

**Issue by cbgbt** [bottlerocket-os/bottlerocket-settings-sdk#24]
An example file looks something like this:

```toml
[extension]
supported-versions = [
    "v1"
]
default-version = "v1"


[v1]
    [v1.validation.cross-validates]

    [v1.templating]
        helpers = []

    [v1.generation.requires]
```

Each extension should have its own configuration file describing the exposed API. We should add the ability to run a config validator in tests.
