### ISSUE TITLE
Feature request: add `settings.kubernetes.node-annotations`

### ISSUE THREAD

**Issue by ginglis13** [bottlerocket-os/bottlerocket-settings-sdk#44]
## What I'd Like

I'd like the ability to set [annotations](https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/) on a node in my Kubernetes cluster via Bottlerocket settings, similar to how I can already set labels on a node. The annotations should be have the same user experience as node labels: https://bottlerocket.dev/en/os/1.20.x/api/settings/kubernetes/#node-labels

As toml:
```toml
[settings.kubernetes.node-annotations]
annotation1 = "foo"
annotation2 = "bar"
```

Via `apiclient`:
```
apiclient set settings.kubernetes.node-annotations.annotation1=foo \ 
 	settings.kubernetes.node-annotations.annotation2=bar
```
